---
name: Galaxy
'on':
  push:
    tags:
      - '*'

jobs:
  galaxy:
    name: galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'ansible-influxdb'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Prepare Ansible
        run: pip3 install ansible-base

      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
