---
name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_ROLENAME: mkayontour.influxdb

    strategy:
      # max-parallel: 4
      matrix:
        distro: [centos7, centos8, debian10, ubuntu2004]
        python: ['3.6']
        ansible: ['2.9', '2.10']
        scenario: [default]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install 'ansible~=${{ matrix.ansible }}'
          python3 -m pip install -r requirements-test.txt

      - name: Test with molecule
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
